# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20160713_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='unpackBox_count',
            field=models.IntegerField(default=0),
        ),
    ]
