# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_outgoing_unpackbox_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='unpackBox_count',
            field=models.IntegerField(null=True),
        ),
    ]
