# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20160714_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='unpackBox_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
