# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20160716_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='unpackBox_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='unpackBox_count',
            field=models.IntegerField(default=0),
        ),
    ]
